# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=64, verbose_name='批次信息')),
                ('batch_code_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
            ],
        ),
        migrations.CreateModel(
            name='CcdCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic_carve_code', models.CharField(max_length=64)),
                ('plastic_battery_check_pic_path', models.FileField(default='null', max_length=128, upload_to='')),
                ('plastic_battery_check_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='检查日期')),
                ('plastic_battery_check_status', models.CharField(choices=[('0', 'default'), ('1', 'ok'), ('2', 'ng')], default='0', max_length=1)),
            ],
        ),
    ]
