# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kzcapi', '0002_auto_20171205_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic_carve_code_1', models.CharField(max_length=64, verbose_name='胶框刻码1')),
                ('plastic_carve_code_2', models.CharField(max_length=64, verbose_name='胶框刻码2')),
                ('heap_battery_core_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='电芯堆叠绑定时间')),
                ('battery_core_scan_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='电芯测试时间')),
                ('battery_core_check_status', models.CharField(choices=[('0', '电芯未测试'), ('1', '电芯测试OK'), ('2', '电芯测试NG')], default='0', max_length=1, verbose_name='电芯测试状态')),
            ],
        ),
        migrations.CreateModel(
            name='BatteryShell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic_carve_code_1', models.CharField(max_length=64, verbose_name='胶框刻码1')),
                ('plastic_carve_code_2', models.CharField(max_length=64, verbose_name='胶框刻码2')),
                ('box_shell_code', models.CharField(max_length=64, verbose_name='壳体码')),
                ('box_shell_code_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='壳体码扫码时间')),
                ('insulation_check_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='绝缘测试时间')),
                ('insulation_check_status', models.CharField(choices=[('0', '绝缘未测试'), ('1', '绝缘测试OK'), ('2', '绝缘测试NG')], default='0', max_length=1, verbose_name='电芯测试状态')),
                ('module_down_scan_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='壳体码扫码时间')),
            ],
        ),
        migrations.AlterField(
            model_name='plasticbox',
            name='plastic_batter_over_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='装电池时间'),
        ),
        migrations.AlterField(
            model_name='plasticbox',
            name='plastic_battery_check_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='图像日期'),
        ),
        migrations.AlterField(
            model_name='plasticbox',
            name='plastic_battery_check_ng_scan_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='电池回流时间'),
        ),
        migrations.AlterField(
            model_name='plasticbox',
            name='plastic_battery_check_pic_path',
            field=models.FileField(default='null', max_length=128, upload_to='', verbose_name='图像路径'),
        ),
        migrations.AlterField(
            model_name='plasticbox',
            name='plastic_battery_check_status',
            field=models.CharField(choices=[('0', '未检查'), ('1', '检测OK'), ('2', '检测NG'), ('3', '人工检测OK')], default='0', max_length=1, verbose_name='CCD状态'),
        ),
        migrations.AlterField(
            model_name='plasticbox',
            name='plastic_carve_scan_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='扫码胶框时间'),
        ),
        migrations.AlterField(
            model_name='plasticbox',
            name='plastic_soldering_a_check_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='A焊接面检查时间'),
        ),
        migrations.AlterField(
            model_name='plasticbox',
            name='plastic_soldering_a_check_status',
            field=models.CharField(choices=[('0', '未检查'), ('1', '检查OK'), ('2', '检查NG'), ('3', '焊接检查OK')], default='0', max_length=1, verbose_name='A焊接面状态'),
        ),
        migrations.AlterField(
            model_name='plasticbox',
            name='plastic_soldering_ab_check_static',
            field=models.CharField(choices=[('0', '未检查'), ('1', '检查OK'), ('2', '检查NG'), ('3', '焊接检查OK')], default='0', max_length=1, verbose_name='焊接面回流检查状态'),
        ),
        migrations.AlterField(
            model_name='plasticbox',
            name='plastic_soldering_b_check_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='B焊接面检查时间'),
        ),
        migrations.AlterField(
            model_name='plasticbox',
            name='plastic_soldering_b_check_status',
            field=models.CharField(choices=[('0', '未检查'), ('1', '检查OK'), ('2', '检查NG'), ('3', '焊接检查OK')], default='0', max_length=1, verbose_name='B焊接面状态'),
        ),
        migrations.AlterField(
            model_name='plasticbox',
            name='plastic_soldering_ng_check_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='焊接面回流时间'),
        ),
        migrations.AlterField(
            model_name='plasticbox',
            name='plastic_type',
            field=models.CharField(choices=[('5x13', '5x13'), ('10x13', '10x13')], default='5x13', max_length=5, verbose_name='类型'),
        ),
    ]
